In [67]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [78]:
dataset = pd.read_csv('dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [79]:
print(x)

[['Spain' nan 48000.0]
 ['Germany' 33.0 54000.0]
 ['France' 35.0 nan]
 ['Thailand' 50.0 89000.0]
 ['Korea' nan 75000.0]
 ['Singapore' 47.0 90000.0]
 ['Spain' 52.0 50000.0]
 ['Germany' 42.0 65000.0]
 ['France' 38.0 79000.0]
 ['Korea' 55.0 nan]
 ['Singapore' 41.0 53000.0]
 ['Indonesia' 49.0 49000.0]
 ['Thailand' 58.0 38000.0]]


In [80]:
print(y)

['Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No']


In [81]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:,1:3])


In [82]:
print(x)

[['Spain' 45.45454545454545 48000.0]
 ['Germany' 33.0 54000.0]
 ['France' 35.0 62727.27272727273]
 ['Thailand' 50.0 89000.0]
 ['Korea' 45.45454545454545 75000.0]
 ['Singapore' 47.0 90000.0]
 ['Spain' 52.0 50000.0]
 ['Germany' 42.0 65000.0]
 ['France' 38.0 79000.0]
 ['Korea' 55.0 62727.27272727273]
 ['Singapore' 41.0 53000.0]
 ['Indonesia' 49.0 49000.0]
 ['Thailand' 58.0 38000.0]]


In [83]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [84]:
print(x)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 45.45454545454545 48000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 33.0 54000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 62727.27272727273]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 50.0 89000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 45.45454545454545 75000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 47.0 90000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 52.0 50000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 42.0 65000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 38.0 79000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 55.0 62727.27272727273]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 41.0 53000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 49.0 49000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 58.0 38000.0]]


In [85]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [86]:
print(y)

[1 1 0 1 1 1 0 1 0 1 0 1 0]


In [87]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x,y, test_size=0.2, random_state=1)

In [88]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 0.0 0.0 41.0 53000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 33.0 54000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 52.0 50000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 45.45454545454545 48000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 42.0 65000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 58.0 38000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 55.0 62727.27272727273]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 38.0 79000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 49.0 49000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 47.0 90000.0]]


In [89]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 35.0 62727.27272727273]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 50.0 89000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 45.45454545454545 75000.0]]


In [90]:
print(y_train)

[0 1 0 1 1 0 1 0 1 1]


In [91]:
print(y_test)

[0 1 1]


In [92]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])


In [93]:
print(x_train)

[[0.0 0.0 0.0 -0.3333333333333333 1.9999999999999998 -0.49999999999999994
  -0.3333333333333333 -0.683269074038741 -0.3946202631638938]
 [0.0 1.0 0.0 -0.3333333333333333 -0.49999999999999994
  -0.49999999999999994 -0.3333333333333333 -1.7666506689109789
  -0.3274248623155528]
 [0.0 0.0 0.0 -0.3333333333333333 -0.49999999999999994 1.9999999999999998
  -0.3333333333333333 0.806380618910586 -0.596206465708917]
 [0.0 0.0 0.0 -0.3333333333333333 -0.49999999999999994 1.9999999999999998
  -0.3333333333333333 -0.08002250416669973 -0.7305972674055992]
 [0.0 1.0 0.0 -0.3333333333333333 -0.49999999999999994
  -0.49999999999999994 -0.3333333333333333 -0.5478463746797113
  0.4117245470161989]
 [0.0 0.0 0.0 -0.3333333333333333 -0.49999999999999994
  -0.49999999999999994 2.9999999999999996 1.6189168150647644
  -1.4025512758890097]
 [0.0 0.0 0.0 2.9999999999999996 -0.49999999999999994
  -0.49999999999999994 -0.3333333333333333 1.2126487169876752
  0.2590077269063329]
 [1.0 0.0 0.0 -0.3333333333333333 

In [94]:
print(x_test)

[[1.0 0.0 0.0 -0.3333333333333333 -0.49999999999999994
  -0.49999999999999994 -0.3333333333333333 -1.4958052701929194
  0.2590077269063329]
 [0.0 0.0 0.0 -0.3333333333333333 -0.49999999999999994
  -0.49999999999999994 2.9999999999999996 0.5355352201925265
  2.0244141673763845]
 [0.0 0.0 0.0 2.9999999999999996 -0.49999999999999994
  -0.49999999999999994 -0.3333333333333333 -0.08002250416669973
  1.0836785554996096]]
